version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: install depedencies
          command: yarn install
      - run:
          name: lint
          command: yarn run lint
      - run:
          name: test
          command: yarn run test
workflows:
  test:
    jobs:
      - test
